[plugins]
ghc = "https://github.com/sestrella/asdf-ghcup.git"


[tools]
# fp-in-clojure
java = "25.0.2"
clojure = "1.12.4.1629"
clj-kondo = "2026.04.15"
cljstyle = "0.17.642"
"github:candid82/joker" = "1.7.1"

# fp-in-scala
sbt = "1.12.11"
coursier = {version = "2.1.24", postinstall = "cs install scalafix:0.14.6 --install-dir ~/.local/bin" }
"github:scalameta/scalafmt" = "3.11.0"

# fp-in-haskell
ghc = "9.14.1"
cabal = "3.16.1.0"
"github:ndmitchell/hlint" = "3.10"
"github:fourmolu/fourmolu" = "0.19.0.1"

# fp-in-ocaml
opam = {version = "2.5.1", postinstall = "opam init -y --disable-sandboxing && opam install -y dune" }
